## Initial positions

In [34]:
#Player 1 starting position: 4
#Player 2 starting position: 8
demoGame = [4, 8]

2-element Array{Int64,1}:
 4
 8

In [2]:
#Player 1 starting position: 10
#Player 2 starting position: 7
game = [10, 7]

2-element Array{Int64,1}:
 10
  7

## Part 1

In [3]:
mutable struct myDice
    i::Int64
    nrolls::Int64
end
function createDice()
   return myDice(1,0) 
end

function rollDice(dice)
    n=0
    dice.nrolls+=3
    if dice.i<99
        n = 3*dice.i + 3
        dice.i+=3
    elseif dice.i == 99
        n = 99 +100+1
        dice.i=2
    elseif dice.i == 100
        n = 100+1+2
        dice.i = 3
    else
        dice.i = dice.i - 100
        n = 3*dice.i + 3
        dice.i+=3
    end
    return n 
end

function simulatePracticeGame(playerStartPos::Array{Int64,1})
    playerPos = copy(playerStartPos)
    playerScore = zeros(Int,size(playerStartPos))
    dice = createDice()
    
    player = 1
    while all(playerScore .< 1000)
        playerPos[player] = mod((playerPos[player]+rollDice(dice))-1,10)+1
        playerScore[player] += playerPos[player]
        player = mod(player,length(playerPos))+1
    end
    return playerScore,dice
end

simulatePracticeGame (generic function with 1 method)

In [4]:
simulatePracticeGame(demoGame)

([1000, 745], myDice(94, 993))

In [5]:
score,dice=simulatePracticeGame(game)

([1006, 907], myDice(100, 999))

In [6]:
minimum(score)*dice.nrolls

906093

## Part 2

In [16]:
sides= [1,2,3]
scores = Array{Int32}(undef,3,3,3)
for i in 1:3,j in 1:3,k in 1:3
    scores[i,j,k] = i+j+k
end
diracDice = [Pair(s,count(x->x==s,scores)) for s in unique(scores)]

7-element Array{Pair{Int32,Int64},1}:
 3 => 1
 4 => 3
 5 => 6
 6 => 7
 7 => 6
 8 => 3
 9 => 1

In [30]:
maxScore = 21
nPlayers = 2
#playerWins = zeros(Int64,nPlayers)

function simulateGame(playerPos::Array{Int64,1},dice::Array{Pair{Int32,Int64},1},playerScore::Array{Int64,1},turn::Int64)
        
    playerWins = zeros(Int64,nPlayers)
    player = mod(turn-1,nPlayers)+1

    for (steps,universes) in dice
        pos = copy(playerPos)
        score = copy(playerScore)
        
        pos[player] = mod((pos[player]+steps)-1,10)+1
        score[player] += pos[player]
        
        if (score[player]>=maxScore)
            playerWins[player] += universes
        else
            playerWins += simulateGame(pos,dice,score,turn+1)*universes
        end
    end
    return playerWins

end

simulateGame (generic function with 1 method)

In [35]:
demoResult=simulateGame(demoGame,diracDice,[0,0],1)

2-element Array{Int64,1}:
 444356092776315
 341960390180808

In [36]:
comparison = [444356092776315,341960390180808]
demoResult==comparison

true

In [37]:
result = simulateGame(game,diracDice,[0,0],1)

2-element Array{Int64,1}:
 274291038026362
 135620348907779

In [38]:
maximum(result)

274291038026362