## Read data

In [2]:
codeLines = readlines("navSubsystem.txt");

In [3]:
codeLinesTest = ["[({(<(())[]>[[{[]{<()<>>";
"[(()[<>])]({[<{<<[]>>(";
"{([(<{}[<>[]}>{[]{[(<()>";
"(((({<>}<{<{<>}{[]{[]{}";
"[[<[([]))<([[{}[[()]]]";
"[{[{({}]{}}([{[{{{}}([]";
"{<[[]]>}<{[{[{[]{()[[[]";
"[<(<(<(<{}))><([]([]()";
"<{([([[(<>()){}]>(<<{{";
"<{([{{}}[<[[[<>{}]]]>[]]"]

10-element Array{String,1}:
 "[({(<(())[]>[[{[]{<()<>>"
 "[(()[<>])]({[<{<<[]>>("
 "{([(<{}[<>[]}>{[]{[(<()>"
 "(((({<>}<{<{<>}{[]{[]{}"
 "[[<[([]))<([[{}[[()]]]"
 "[{[{({}]{}}([{[{{{}}([]"
 "{<[[]]>}<{[{[{[]{()[[[]"
 "[<(<(<(<{}))><([]([]()"
 "<{([([[(<>()){}]>(<<{{"
 "<{([{{}}[<[[[<>{}]]]>[]]"

## Part 1

4-element Array{Char,1}:
 ')'
 ']'
 '}'
 '>'

determine which lines are incomplete vs. corrupted

In [43]:
function findCorruptLines(allLines)
    
    validOpenings = ['(','[','{','<']
    validClosings = [')',']','}','>']
    validPairs = Dict(zip(validOpenings,validClosings))
    
    corruptedLines = Array{String}(undef,0)
    for line in allLines
        currentOpen = Array{Char}(undef,length(line))
        nOpen = 0
        for c in reverse(line)
            #if closing, add to list
            if (c in values(validPairs))
                nOpen +=1
                currentOpen[nOpen] = c
            #if Opening, check if nOpen >0, incomplete otherwise
            else 
                if nOpen > 0
                    #check if opening matches current innermost closing, corrupt otherwise
                    if validPairs[c] == currentOpen[nOpen]
                        nOpen -=1 
                    else
                        push!(corruptedLines,line)
                        break
                    end
                end
            end
        end
    end
    return corruptedLines
end

function findFirstCorruptionInLine(allLines)
    
    validOpenings = ['(','[','{','<']
    validClosings = [')',']','}','>']
    validPairs = Dict(zip(validClosings,validOpenings))
    
    score = 0
    scoreCard = Dict(zip(validClosings,[3,57,1197,25137]))
    
    for line in allLines
        currentOpen = Array{Char}(undef,length(line))
        nOpen = 0
        for c in line
            #if opening, add to list
            if (c in values(validPairs))
                nOpen +=1
                currentOpen[nOpen] = c
            #if closing, check if opening matches current innermost opening, corrupt otherwise
            else 
                if validPairs[c] == currentOpen[nOpen]
                    nOpen -=1 
                else
                    score += scoreCard[c]
                    break
                end
            end
        end
    end
    
    return score
end

findFirstCorruptionInLine (generic function with 1 method)

In [44]:
corruptedLinesTest = findCorruptLines(codeLinesTest)
testScore = findFirstCorruptionInLine(corruptedLinesTest)
println(testScore)
corruptedLinesTest

26397


5-element Array{String,1}:
 "{([(<{}[<>[]}>{[]{[(<()>"
 "[[<[([]))<([[{}[[()]]]"
 "[{[{({}]{}}([{[{{{}}([]"
 "[<(<(<(<{}))><([]([]()"
 "<{([([[(<>()){}]>(<<{{"

In [45]:
corruptedLines = findCorruptLines(codeLines)
score = findFirstCorruptionInLine(corruptedLines)

392421

## Part 2

In [47]:
incompLinesTest = setdiff(codeLinesTest,corruptedLinesTest)

5-element Array{String,1}:
 "[({(<(())[]>[[{[]{<()<>>"
 "[(()[<>])]({[<{<<[]>>("
 "(((({<>}<{<{<>}{[]{[]{}"
 "{<[[]]>}<{[{[{[]{()[[[]"
 "<{([{{}}[<[[[<>{}]]]>[]]"

In [49]:
size(incompLinesTest),size(corruptedLinesTest),size(codeLinesTest)

((5,), (5,), (10,))

In [48]:
incompLines = setdiff(codeLines,corruptedLines);

In [50]:
size(incompLines),size(corruptedLines),size(codeLines)

((55,), (55,), (110,))

In [83]:
function completeLines(allLines)
    
    validOpenings = ['(','[','{','<']
    validClosings = [')',']','}','>']
    validPairs = Dict(zip(validClosings,validOpenings))
    scoreCard = Dict(zip(validOpenings,[1,2,3,4]))
    
    currentOpen = Array{Char}(undef,length(allLines[1]))
    scores = zeros(Int,length(allLines))
    
    
    for (i,line) in enumerate(allLines)
        nOpen = 0
        
        for c in line
            #if opening, add to list
            if (c in values(validPairs))
                nOpen +=1
                currentOpen[nOpen] = c
            #if closing, go back one opening
            else 
                nOpen -=1  
            end
        end
        
        for j in nOpen:-1:1
            scores[i] *= 5
            scores[i] += scoreCard[currentOpen[j]]
        end
    end
    
    return scores
end

completeLines (generic function with 1 method)

In [84]:
scoresTest = completeLines(incompLinesTest)
sort!(scoresTest)[length(scoresTest)÷2+1]

288957

In [85]:
scores = completeLines(incompLines)
sort!(scores)[length(scores)÷2+1]

2769449099